feat(students): Add student registration by CSV import
desenvolvendo-me/ticket-event pull request #120
Opened 2023-10-24 01:02 UTC by cassiosantana

2023-10-25 12:35 UTC, marcodotcastro requested changes

2023-10-25 12:35 UTC, marcodotcastro commented on app/businesses/students/csv_student_register.rb
> +    def create_student(row)
Refatore o código, pois a tarefa de criar estudante de csv está duplicado.


Esse é o local: https://github.com/desenvolvendo-me/ticket-event/blob/release/v0.1/app/businesses/tickets/builders.rb#L23

2023-10-27 20:39 UTC, cassiosantana commented on app/businesses/students/csv_student_register.rb
> +    def create_student(row)
Feito

2023-10-28 13:00 UTC, PhilipeeX approved these changes

2023-10-28 15:00 UTC, marcodotcastro approved these changes

2023-10-28 15:00 UTC, merged