Feature/125 permitir estudante visualize uma imagem evento
desenvolvendo-me/ticket-event pull request #155
Opened 2023-11-03 19:13 UTC by ricardofelipe7

2023-11-03 19:46 UTC, marcodotcastro requested changes
Me explique por que está usando essa gem image_processing.

2023-11-03 20:08 UTC, ricardofelipe7 commented
Ajuda no processamento de image, para redimensionar imagem de alta qualidade para uploads na aplicação.

https://www.youtube.com/watch?v=1cw6qO1EYGw&ab_channel=Deanin
https://github.com/janko/image_processing

2023-11-03 20:25 UTC, marcodotcastro commented on app/models/event.rb
> +  def image_as_config
Crie metodos com esse padrão, mas primeiro verifique se a gem já não faz isso

image_to_medium
image_to_small
image_to_large

2023-11-06 19:59 UTC, marcodotcastro approved these changes

2023-11-06 19:59 UTC, merged