Feature/161 permitir que estudante logue no sistema
desenvolvendo-me/ticket-event pull request #169
Opened 2023-11-09 19:37 UTC by ricardofelipe7

2023-11-09 19:59 UTC, PhilipeeX approved these changes

2023-11-09 19:59 UTC, PhilipeeX commented
Acho que só faltou o seeds de student_user

2023-11-10 10:54 UTC, cassiosantana requested changes

2023-11-10 10:54 UTC, cassiosantana commented on app/views/layouts/_top_menu.html.erb
> +          <%= link_to "Login Student", student_user_session_path, method: :post, class: "block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text
Alterar o helper da rota para `new_student_user_session_path` sem o método post como o helper de login do manager.

2023-11-10 11:25 UTC, ricardofelipe7 commented on app/views/layouts/_top_menu.html.erb
> +          <%= link_to "Login Student", student_user_session_path, method: :post, class: "block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text
Entendi @cassiosantana, já realizei a mudança.

2023-11-10 17:38 UTC, merged