Feature/215 remover prizedraw do ticket
desenvolvendo-me/ticket-event pull request #216
Opened 2024-02-18 22:25 UTC by osksergio

#215

2024-02-19 00:31 UTC, victoroliveira59 requested changes
È necessario pois ainda precisa ser feito algumas  alterações referente ao prize_draw_id ainda existe resquicios da associação no seed e no model de ticket.

2024-02-22 17:17 UTC, osksergio commented
> È necessario pois ainda precisa ser feito algumas alterações referente ao prize_draw_id ainda existe resquicios da associação no seed e no model de ticket.

- [x] Correção das associações entre prize_dray e ticket
- [x] Seeds foram modificados
- [x] Removidos alguns parâmetros de campos inexistentes (controller: ticket)

2024-02-22 17:19 UTC, victoroliveira59 commented
> È necessario pois ainda precisa ser feito algumas alterações referente ao prize_draw_id ainda existe resquicios da associação no seed e no model de ticket.

2024-02-22 17:19 UTC, victoroliveira59 approved these changes

2024-02-23 17:56 UTC, marcodotcastro approved these changes

2024-02-23 17:58 UTC, merged