Feature/event search
desenvolvendo-me/ticket-event pull request #220
Opened 2024-02-26 22:48 UTC by marcoaspeixoto

2024-02-27 18:35 UTC, PhilipeeX approved these changes

2024-02-28 12:05 UTC, marcodotcastro requested changes
Altere a filtro pela gem ransack

2024-03-06 21:25 UTC, marcodotcastro commented on app/views/manager/events/index.html.erb
> +              <%= f.search_field :name_or_description_cont, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full pl-
Remova o placeholder

2024-03-06 21:26 UTC, marcodotcastro commented on config/locales/views/manager/event.pt-BR.yml
> +          enter_name_description: "Nome ou descrição"
Remova esse enter_name_description

2024-03-06 21:26 UTC, marcodotcastro commented on config/routes.rb
> +    get 'events/search_events', to: 'events#search_events', as: 'search_events'
Remova essa rota

2024-03-11 22:59 UTC, marcodotcastro approved these changes

2024-03-11 22:59 UTC, merged