Feature/223 permitir que o estudante ao cadastrar o login ele seja vinculado ao cadastro do estudante
desenvolvendo-me/ticket-event pull request #224
Opened 2024-03-01 11:24 UTC by eskokado

2024-03-01 11:55 UTC, marcodotcastro commented on app/controllers/external/lessons_controller.rb
>      end
Não adicione regra de negócio no controller, mova ou crie um business

2024-03-01 11:56 UTC, marcodotcastro commented on app/models/lesson.rb
> +    student_lesson.present? && student_lesson.last.status == "finished"
Não adicione regra de negócio no model, mova ou crie um business

2024-03-01 11:56 UTC, marcodotcastro commented on app/models/student_user.rb
> +    end
Não adicione regra de negócio no model, mova ou crie um business

2024-03-01 11:57 UTC, marcodotcastro commented on app/businesses/certificates/builder.rb
> +        "No name"
Move para o i18n

2024-03-01 11:59 UTC, marcodotcastro requested changes
Realizar ajustes. Não esquecer de criar testes para os businesses.

2024-03-01 19:03 UTC, eskokado commented
Realizado os ajustes e os testes.

2024-03-04 10:15 UTC, eskokado commented on app/controllers/external/lessons_controller.rb
>      end
refatorado para business

2024-03-04 10:16 UTC, eskokado commented on app/models/lesson.rb
> +    student_lesson.present? && student_lesson.last.status == "finished"
refatorado para business

2024-03-04 10:16 UTC, eskokado commented on app/models/student_user.rb
> +    end
refatorado para business

2024-03-04 10:17 UTC, eskokado commented on app/businesses/certificates/builder.rb
> +        "No name"
aplicado i18n

2024-03-04 23:33 UTC, marcodotcastro commented on app/businesses/lessons/lesson_service.rb
Usar o padrão de BusinesseApplication

2024-03-04 23:33 UTC, marcodotcastro commented on app/businesses/students/student_user_service.rb
Usar o padrão de BusinesseApplication

2024-03-05 11:34 UTC, eskokado commented on app/businesses/lessons/lesson_service.rb
Applicado

2024-03-05 11:34 UTC, eskokado commented on app/businesses/students/student_user_service.rb
Applicado

2024-03-11 20:58 UTC, marcodotcastro approved these changes

2024-03-11 20:58 UTC, merged