Feature/46 escolher um ingresso
desenvolvendo-me/ticket-event pull request #50
Opened 2023-08-31 14:19 UTC by marcodotcastro

2023-09-02 15:24 UTC, cassiosantana commented on app/views/admin/tickets/select_student_csv.html.erb
> +            <td><%= f.select :event_id, options_for_select(Event.all.collect { |event| [event.name, event.id] }), prompt: "Selecione o evento" %></td>
Adicionar tradução.

2023-09-04 21:09 UTC, marcodotcastro commented on app/admin/events.rb
> +  end
Esse código é necessário para funcionar um view no active admin.

2023-09-04 22:35 UTC, cassiosantana requested changes

2023-09-04 22:35 UTC, cassiosantana commented on app/views/admin/events/select_template_ticket.html.erb
> +        <% end %>
Corrigir indentação.

2023-09-04 22:35 UTC, cassiosantana commented on app/views/admin/tickets/select_student_csv.html.erb
>          <% end %>
Corrigir indentação.

2023-09-04 22:46 UTC, PhilipeeX commented on .gitignore
Não commitar .gitignore

2023-09-04 22:51 UTC, PhilipeeX approved these changes

2023-09-04 22:53 UTC, PhilipeeX commented on .gitignore
Devemos commitar o .gitignore?

2023-09-04 23:00 UTC, cassiosantana commented on .gitignore
Sim

2023-09-04 23:19 UTC, cassiosantana approved these changes

2023-09-05 14:41 UTC, merged