Feature/53 o estudante deve ter acesso as aulas
desenvolvendo-me/ticket-event pull request #56
Opened 2023-09-04 12:55 UTC by PhilipeeX

2023-09-04 14:56 UTC, marcodotcastro commented on app/controllers/checkins_controller.rb
> +  #skip_before_action :authenticate_user!, :only => [:checked, :search, :form]
Remove

2023-09-04 14:57 UTC, marcodotcastro commented on app/helpers/lessons_helper.rb
Mover para camada de business

2023-09-04 15:05 UTC, marcodotcastro requested changes
- Remover o webscrapping
- Verificar a identidade

2023-09-04 21:05 UTC, marcodotcastro commented on app/businesses/lessons/youtube_video_embedder.rb
> +  class YoutubeVideoEmbedder
Altere o nome somente para Embedder

2023-09-04 21:06 UTC, marcodotcastro commented on app/businesses/lessons/lesson_validator.rb
> +  class LessonValidator
Altere o nome para somente Validator

2023-09-04 21:49 UTC, cassiosantana commented on app/businesses/lessons/youtube_video_embedder.rb
> +        raise ArgumentError, 'URL do YouTube em formato desconhecido ou inválido.'
Adicionar tradução.

2023-09-04 21:49 UTC, cassiosantana commented on app/models/event.rb
> +  has_many :lessons
Qual o comportamento desejado ao excluir um Event? Sem expliciar teremos erro de restrição de chave estrangeira pelo fato do Event não existir mais.

2023-09-05 15:10 UTC, marcodotcastro approved these changes

2023-09-05 15:10 UTC, merged